#!/bin/bash

git checkout master

git pull origin master

git submodule init
git submodule update --remote
git add .
git commit --allow-empty -m 'rebuild pages: '$(cat .git/refs/heads/blogs)

git push origin master

git checkout blogs
